// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFtvAovsverYPOzzJ5AaVb9AJ2_30yAs',
    appId: '1:780261785606:web:d0b7cc05049887b5ed4387',
    messagingSenderId: '780261785606',
    projectId: 'iic-connect-ea888',
    authDomain: 'iic-connect-ea888.firebaseapp.com',
    storageBucket: 'iic-connect-ea888.firebasestorage.app',
    measurementId: 'G-YY1FDTYKEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2JlrLnzdqGaFXAXfweyqGPv8CTJ9ZWr0',
    appId: '1:780261785606:android:6c0342b036ca352eed4387',
    messagingSenderId: '780261785606',
    projectId: 'iic-connect-ea888',
    storageBucket: 'iic-connect-ea888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiElBDRMp9PSQRFwihHRxhbi9d1rpYR0o',
    appId: '1:780261785606:ios:9841fba5e226ea07ed4387',
    messagingSenderId: '780261785606',
    projectId: 'iic-connect-ea888',
    storageBucket: 'iic-connect-ea888.firebasestorage.app',
    iosBundleId: 'com.manuraj.iicConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiElBDRMp9PSQRFwihHRxhbi9d1rpYR0o',
    appId: '1:780261785606:ios:9841fba5e226ea07ed4387',
    messagingSenderId: '780261785606',
    projectId: 'iic-connect-ea888',
    storageBucket: 'iic-connect-ea888.firebasestorage.app',
    iosBundleId: 'com.manuraj.iicConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnFtvAovsverYPOzzJ5AaVb9AJ2_30yAs',
    appId: '1:780261785606:web:107bbbf366335181ed4387',
    messagingSenderId: '780261785606',
    projectId: 'iic-connect-ea888',
    authDomain: 'iic-connect-ea888.firebaseapp.com',
    storageBucket: 'iic-connect-ea888.firebasestorage.app',
    measurementId: 'G-M9PW50TQ14',
  );
}
